name: Remove Development Docker Images
on: delete

jobs:    
  purge-image:
    if: github.event.ref_type == 'branch'
    name: Delete image from ghcr.io
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name (merge)
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${{ github.event.ref }} | tr / -)" >> $GITHUB_ENV
      - name: Delete image
        uses: actions/delete-package-versions@v3
        with: 
          owner: 'breadboi'
          repo: 'personal-website'
          package-name: 'personal-website:${{ env.BRANCH_NAME }}'
          token: ${{ secrets.DOCKERDEL }}
#         uses: bots-house/ghcr-delete-image-action@v1.0.0
#         with:
#         # NOTE: at now only orgs is supported
#           owner: breadboi
#           name: rm-old-image
#         # NOTE: using Personal Access Token
#           token: ${{ secrets.DOCKERDEL }}
#           tag: ${{ env.BRANCH_NAME }}
